build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "HACS: get"
  org.opencontainers.image.description: "Get HCS"
  org.opencontainers.image.source: "https://github.com/javishome/get_hacs"
  org.opencontainers.image.licenses: "MIT License"
